export interface ContentData {
  topic: string;
  target_keyword: string | null;
  secondary_keywords: string[] | null;
  search_intent: string | null;
  recommended_word_count: number | null;
  meta_title: string | null;
  meta_description: string | null;
  og_title: string | null;
  og_description: string | null;
  full_draft: string | null;
  word_count: number | null;
  outline: OutlineItem[] | null;
}

export interface OutlineItem {
  level: string;
  heading: string;
  points: string[];
}

export function generateMarkdown(content: ContentData): string {
  const lines: string[] = [];

  // Header
  const h1 =
    content.outline?.find((item) => item.level === "h1")?.heading ||
    content.topic;
  lines.push(`# ${h1}`);
  lines.push("");

  // SEO Brief
  if (content.target_keyword) {
    lines.push(`**Target Keyword:** ${content.target_keyword}`);
  }
  if (content.word_count) {
    lines.push(`**Word Count:** ${content.word_count}`);
  }
  if (content.search_intent) {
    lines.push(`**Search Intent:** ${content.search_intent}`);
  }
  if (content.secondary_keywords?.length) {
    lines.push(
      `**Secondary Keywords:** ${content.secondary_keywords.join(", ")}`
    );
  }
  lines.push("");

  // Full draft
  if (content.full_draft) {
    lines.push(content.full_draft);
    lines.push("");
  }

  // Meta tags
  if (content.meta_title || content.meta_description) {
    lines.push("---");
    lines.push("");
    lines.push("## Meta Tags");
    lines.push("");
    if (content.meta_title) {
      lines.push(`**Meta Title:** ${content.meta_title}`);
    }
    if (content.meta_description) {
      lines.push(`**Meta Description:** ${content.meta_description}`);
    }
    if (content.og_title) {
      lines.push(`**OG Title:** ${content.og_title}`);
    }
    if (content.og_description) {
      lines.push(`**OG Description:** ${content.og_description}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by ContentForge*");

  return lines.join("\n");
}

export function generatePlainText(content: ContentData): string {
  const lines: string[] = [];

  const h1 =
    content.outline?.find((item) => item.level === "h1")?.heading ||
    content.topic;
  lines.push(h1);
  lines.push("=".repeat(h1.length));
  lines.push("");

  if (content.target_keyword) {
    lines.push(`Target Keyword: ${content.target_keyword}`);
  }
  if (content.word_count) {
    lines.push(`Word Count: ${content.word_count}`);
  }
  if (content.search_intent) {
    lines.push(`Search Intent: ${content.search_intent}`);
  }
  if (content.secondary_keywords?.length) {
    lines.push(`Secondary Keywords: ${content.secondary_keywords.join(", ")}`);
  }
  lines.push("");

  if (content.full_draft) {
    // Strip markdown formatting for plain text
    const plainDraft = content.full_draft
      .replace(/^#{1,6}\s+/gm, "") // Remove heading markers
      .replace(/\*\*(.*?)\*\*/g, "$1") // Remove bold
      .replace(/\*(.*?)\*/g, "$1") // Remove italic
      .replace(/`(.*?)`/g, "$1"); // Remove inline code
    lines.push(plainDraft);
    lines.push("");
  }

  if (content.meta_title || content.meta_description) {
    lines.push("-".repeat(40));
    lines.push("");
    lines.push("META TAGS");
    lines.push("-".repeat(9));
    lines.push("");
    if (content.meta_title) {
      lines.push(`Meta Title: ${content.meta_title}`);
    }
    if (content.meta_description) {
      lines.push(`Meta Description: ${content.meta_description}`);
    }
    if (content.og_title) {
      lines.push(`OG Title: ${content.og_title}`);
    }
    if (content.og_description) {
      lines.push(`OG Description: ${content.og_description}`);
    }
    lines.push("");
  }

  lines.push("-".repeat(40));
  lines.push("Generated by ContentForge");

  return lines.join("\n");
}
